import vazirFont from "@/constants/localFont";
import "./globals.css";
import { ProductProvider } from "@/context/ProductsContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: {
    template: "Homex  |   %s",
    default: "Homex ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans`}>
        <ProductProvider>
          <Navbar />
          {children}
          <Footer />
        </ProductProvider>
      </body>
    </html>
  );
}
